version: '3.7'
networks:
    sqli_linux_network:
        ipam:
            config:
              - subnet: 172.19.0.0/16
services:
    sql_victim_db_mariadb:
        container_name: "sql.victim.db.mariadb.tld"
        image: "mariadb:10.4.6"
        environment:
            TZ: "Europe/Berlin"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
        volumes:
            - type: bind
              source: ./sql_victim_db_mariadb/scripts
              target: /docker-entrypoint-initdb.d/
        networks:
            sqli_linux_network:
              ipv4_address: 172.19.0.2
    sql_victim_webapp_php:
        container_name: "sql.victim.webapp.php.tld"
        build: "./sql_victim_webapp_php"
        ports:
            - "127.0.0.1:8781:80"
        volumes:
            - type: bind
              source: ./sql_victim_webapp_php/src
              target: /var/www/html
        networks:
            sqli_linux_network:
              ipv4_address: 172.19.0.3
        links:
            - "sql_victim_db_mariadb"
    nosql_victim_webapp_php:
        container_name: "nosql.victim.webapp.php.tld"
        build: "./nosql_victim_webapp_php"
        ports:
            - "127.0.0.1:8782:80"
        volumes:
            - type: bind
              source: ./nosql_victim_webapp_php/src
              target: /var/www/html
        networks:
            sqli_linux_network:
                ipv4_address: 172.19.0.4
        links:
            - "nosql_victim_db_mongo"
    nosql_victim_db_mongo:
        container_name: "nosql.victim.db.mongo.tld"
        image: "mongo:3.4.24"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: nosqlidb
        volumes:
            - type: bind
              source: ./nosql_victim_db_mongo/scripts
              target: /docker-entrypoint-initdb.d/
        networks:
            sqli_linux_network:
                ipv4_address: 172.19.0.5

