version: '3.7'
networks:
    sqli_linux_network:
        ipam:
            config:
              - subnet: 172.19.0.0/16
services:
    sqli_victim_db_mariadb:
        container_name: "sqli.victim.db.mariadb.tld"
        image: "mariadb:10.4.6"
        environment:
            TZ: "Europe/Berlin"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
        volumes:
            - type: bind
              source: ./sqli_victim_db_mariadb/scripts
              target: /docker-entrypoint-initdb.d/
        networks:
            sqli_linux_network:
              ipv4_address: 172.19.0.2

    sqli_victim_webapp_php:
        container_name: "sqli.victim.webapp.php.tld"
        build: "./sqli_victim_webapp_php"
        ports:
        - "127.0.0.1:8781:80"
        environment:
        - SERVER_HOST_EXTERNAL_IP=127.0.0.1
        - SERVER_HOST_EXTERNAL_PORT=8781
        - SERVER_DOCKER_INTERNAL_IP=172.19.0.3
        - SERVER_DOCKER_INTERNAL_PORT=80
        volumes:
        - type: bind
          source: ./sqli_victim_webapp_php/src
          target: /var/www/html
        networks:
         sqli_linux_network:
          ipv4_address: 172.19.0.3
        links:
        - "sqli_victim_db_mariadb"

    nosqli_victim_webapp_php:
        container_name: "nosqli.victim.webapp.php.tld"
        build: "./nosqli_victim_webapp_php"
        ports:
        - "127.0.0.1:8783:80"
        environment:
        - SERVER_HOST_EXTERNAL_IP=127.0.0.1
        - SERVER_HOST_EXTERNAL_PORT=8783
        - SERVER_DOCKER_INTERNAL_IP=172.19.0.4
        - SERVER_DOCKER_INTERNAL_PORT=80
        volumes:
        - type: bind
          source: ./nosqli_victim_webapp_php/src
          target: /var/www/html
        networks:
          sqli_linux_network:
           ipv4_address: 172.19.0.4
        links:
        - "nosqli_victim_db_mongo"

    nosqli_victim_db_mongo:
        container_name: "nosqli.victim.db.mongo.tld"
        image: "mongo:3.4.24"
        restart: always
        environment:
         MONGO_INITDB_ROOT_USERNAME: root
         MONGO_INITDB_ROOT_PASSWORD: password
         MONGO_INITDB_DATABASE: nosqlidb
        volumes:
        - type: bind
          source: ./nosqli_victim_db_mongo/scripts
          target: /docker-entrypoint-initdb.d/
        networks:
         sqli_linux_network:
          ipv4_address: 172.19.0.5

