version: '3.7'
networks:
    sqli_linux_network:
        ipam:
            config:
              - subnet: 172.19.0.0/16
services:
    victim_server_db_mariadb:
        container_name: "victim.db.mariadb.tld"
        image: "mariadb:10.4.6"
        environment:
            TZ: "Europe/Berlin"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
        volumes:
            - type: bind
              source: ./victim_server_db_mariadb/scripts
              target: /docker-entrypoint-initdb.d/
        networks:
            sqli_linux_network:
              ipv4_address: 172.19.0.2
    victim_server_sqli_php:
        container_name: "victim.sqli.php.tld"
        build: "./victim_server_sqli_php"
        ports:
            - "127.0.0.1:8781:80"
        volumes:
            - type: bind
              source: ./victim_server_sqli_php/src
              target: /var/www/html
        networks:
            sqli_linux_network:
              ipv4_address: 172.19.0.3
        links:
            - "victim_server_db_mariadb"
